- hosts: kali-pi
  remote_user: root

  tasks:
    - name: Ensure aptitude is present using apt
      apt:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Ensure nmap is installed
      apt:
        name: nmap
        state: latest
        update_cache: yes

# Install lan-auditor

    - name: Create lan-auditor directory
      file:
        path: /opt/lan-auditor
        state: directory

    - name: Create lan-auditor log directory
      file:
        path: /var/log/lan-auditor
        state: directory

    - name: Create lan-auditor/scans directory
      file:
        path: /opt/lan-auditor/scans
        state: directory

    - name: Create lan-auditor/utils directory
      file:
        path: /opt/lan-auditor/utils
        state: directory

    - name: Copy host_scan.sh
      copy:
        src: ../../scripts/scans/host_scan.sh
        dest: /opt/lan-auditor/scans/host_scan.sh
        mode: '0755'

    - name: Copy unique_ips.sh
      copy:
        src: ../../scripts/utils/unique_ips.sh
        dest: /opt/lan-auditor/utils/unique_ips.sh
        mode: '0755'

    - name: Copy unique_host_ips.sh
      copy:
        src: ../../scripts/utils/unique_host_ips.sh
        dest: /opt/lan-auditor/utils/unique_host_ips.sh
        mode: '0755'

    - name: Run a host_scan every 5 minutes
      cron:
        name: "host_scan"
        minute: "*/5"
        job: "/opt/lan-auditor/scans/host_scan.sh"
